// <auto-generated />
using System;
using EcoNexus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoNexus.Infrastructure.Migrations
{
    [DbContext(typeof(EcoNexusDbContext))]
    [Migration("20260925101259_AddAssistantInteractions")]
    partial class AddAssistantInteractions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoNexus.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("AcknowledgedAt");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AcknowledgedBy");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Message");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("RaisedAt");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ResolvedAt");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ResolvedBy");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Severity");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StationId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("StationId")
                        .HasDatabaseName("IX_Alerts_StationId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Alerts_Status");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.AssistantInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("Answer");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("LatencyMs");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("OccurredAt");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProviderName");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Question");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ToolName");

                    b.Property<string>("ToolParametersJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("ToolParametersJson");

                    b.Property<string>("ToolResultJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ToolResultJson");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AssistantInteractions_UserId");

                    b.HasIndex("UserId", "OccurredAt")
                        .HasDatabaseName("IX_AssistantInteractions_UserId_OccurredAt");

                    b.ToTable("AssistantInteractions", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.CitizenProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("CurrentStreakDays")
                        .HasColumnType("int")
                        .HasColumnName("CurrentStreakDays");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("DisplayName");

                    b.Property<string>("HomeAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("HomeAddress");

                    b.Property<double?>("HomeLatitude")
                        .HasColumnType("float")
                        .HasColumnName("HomeLatitude");

                    b.Property<double?>("HomeLongitude")
                        .HasColumnType("float")
                        .HasColumnName("HomeLongitude");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastUpdatedAt");

                    b.Property<DateOnly?>("LastVisitDate")
                        .HasColumnType("date")
                        .HasColumnName("LastVisitDate");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_CitizenProfiles_UserId");

                    b.ToTable("CitizenProfiles", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.CitizenReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("AcknowledgedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Description");

                    b.Property<DateTimeOffset>("FiledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("FiledAt");

                    b.Property<Guid>("FiledByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FiledByUserId");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("PhotoUrl");

                    b.Property<string>("ReportType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ReportType");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("ResolutionNote");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ResolvedAt");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StationId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("FiledByUserId")
                        .HasDatabaseName("IX_CitizenReports_FiledByUserId");

                    b.HasIndex("ReportType")
                        .HasDatabaseName("IX_CitizenReports_ReportType");

                    b.HasIndex("StationId")
                        .HasDatabaseName("IX_CitizenReports_StationId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_CitizenReports_Status");

                    b.ToTable("CitizenReports", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.CollectionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CompletedAt");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ScheduledFor");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("StartedAt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("VehicleId");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_CollectionJobs_Status");

                    b.HasIndex("VehicleId", "ScheduledFor")
                        .HasDatabaseName("IX_CollectionJobs_VehicleId_ScheduledFor");

                    b.ToTable("CollectionJobs", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.CollectionVehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Capacity")
                        .HasColumnType("float")
                        .HasColumnName("CapacityKilograms");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RegistrationNumber");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectionVehicles_RegistrationNumber");

                    b.ToTable("CollectionVehicles", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.FacilityIntake", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FacilityId");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Material");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("RecordedAt");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Stage");

                    b.Property<DateTimeOffset?>("StageUpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("StageUpdatedAt");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("WeightKilograms");

                    b.HasKey("Id");

                    b.HasIndex("Stage")
                        .HasDatabaseName("IX_FacilityIntakes_Stage");

                    b.HasIndex("FacilityId", "RecordedAt")
                        .HasDatabaseName("IX_FacilityIntakes_FacilityId_RecordedAt");

                    b.ToTable("FacilityIntakes", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.GreenPointTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CitizenProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CitizenProfileId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("OccurredAt");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Reason");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RelatedEntityId");

                    b.Property<int>("SignedDelta")
                        .HasColumnType("int")
                        .HasColumnName("SignedDelta");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Source");

                    b.HasKey("Id");

                    b.HasIndex("Reason")
                        .HasDatabaseName("IX_GreenPointTransactions_Reason");

                    b.HasIndex("Source")
                        .HasDatabaseName("IX_GreenPointTransactions_Source");

                    b.HasIndex("CitizenProfileId", "OccurredAt")
                        .HasDatabaseName("IX_GreenPointTransactions_CitizenProfileId_OccurredAt");

                    b.HasIndex("CitizenProfileId", "Reason", "OccurredAt")
                        .HasDatabaseName("IX_GreenPointTransactions_CitizenProfileId_Reason_OccurredAt");

                    b.ToTable("GreenPointTransactions", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.RecyclingFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<double>("DailyCapacity")
                        .HasColumnType("float")
                        .HasColumnName("DailyCapacityKilograms");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastUpdatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_RecyclingFacilities_Status");

                    b.ToTable("RecyclingFacilities", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ExpiresAt");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("ReplacedByTokenHash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("RevokedAt");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("TokenHash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_RefreshTokens_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CostInPoints")
                        .HasColumnType("int")
                        .HasColumnName("CostInPoints");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Rewards_IsActive");

                    b.ToTable("Rewards", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.RouteStop", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("CollectedWeight")
                        .HasColumnType("float")
                        .HasColumnName("CollectedWeightKilograms");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CompletedAt");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("JobId");

                    b.Property<int>("Sequence")
                        .HasColumnType("int")
                        .HasColumnName("Sequence");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StationId");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Sequence")
                        .HasDatabaseName("IX_RouteStops_JobId_Sequence");

                    b.ToTable("RouteStops", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.StationReading", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BatteryPercent")
                        .HasColumnType("int")
                        .HasColumnName("BatteryPercent");

                    b.Property<double>("FillLevel")
                        .HasColumnType("float")
                        .HasColumnName("FillLevelPercent");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("RecordedAt");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StationId");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("float")
                        .HasColumnName("TemperatureCelsius");

                    b.HasKey("Id");

                    b.HasIndex("StationId", "RecordedAt")
                        .HasDatabaseName("IX_StationReadings_StationId_RecordedAt");

                    b.ToTable("StationReadings", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.WasteClassification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Category");

                    b.Property<Guid>("CitizenProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CitizenProfileId");

                    b.Property<DateTimeOffset>("ClassifiedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ClassifiedAt");

                    b.Property<double>("Confidence")
                        .HasColumnType("float")
                        .HasColumnName("Confidence");

                    b.Property<string>("DisposalInstruction")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DisposalInstruction");

                    b.Property<string>("ImageReference")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("ImageReference");

                    b.Property<bool>("IsCompostable")
                        .HasColumnType("bit")
                        .HasColumnName("IsCompostable");

                    b.Property<bool>("IsRecyclable")
                        .HasColumnType("bit")
                        .HasColumnName("IsRecyclable");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProviderName");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_WasteClassifications_Category");

                    b.HasIndex("CitizenProfileId", "ClassifiedAt")
                        .HasDatabaseName("IX_WasteClassifications_CitizenProfileId_ClassifiedAt");

                    b.HasIndex("ProviderName", "Confidence")
                        .HasDatabaseName("IX_WasteClassifications_ProviderName_Confidence");

                    b.ToTable("WasteClassifications", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.WasteStation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Capacity")
                        .HasColumnType("float")
                        .HasColumnName("CapacityKilograms");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Code");

                    b.Property<double>("CurrentFill")
                        .HasColumnType("float")
                        .HasColumnName("CurrentFillPercent");

                    b.Property<DateTimeOffset?>("LastCollectedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastCollectedAt");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastUpdatedAt");

                    b.Property<string>("PrimaryCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("PrimaryCategory");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_WasteStations_Code");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_WasteStations_Status");

                    b.ToTable("WasteStations", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.FacilityIntake", b =>
                {
                    b.HasOne("EcoNexus.Domain.Entities.RecyclingFacility", null)
                        .WithMany("Intakes")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.GreenPointTransaction", b =>
                {
                    b.HasOne("EcoNexus.Domain.Entities.CitizenProfile", null)
                        .WithMany("Transactions")
                        .HasForeignKey("CitizenProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.RecyclingFacility", b =>
                {
                    b.OwnsOne("EcoNexus.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("RecyclingFacilityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.HasKey("RecyclingFacilityId");

                            b1.ToTable("RecyclingFacilities");

                            b1.WithOwner()
                                .HasForeignKey("RecyclingFacilityId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.RouteStop", b =>
                {
                    b.HasOne("EcoNexus.Domain.Entities.CollectionJob", null)
                        .WithMany("Stops")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.StationReading", b =>
                {
                    b.HasOne("EcoNexus.Domain.Entities.WasteStation", null)
                        .WithMany("Readings")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.WasteClassification", b =>
                {
                    b.HasOne("EcoNexus.Domain.Entities.CitizenProfile", null)
                        .WithMany("Classifications")
                        .HasForeignKey("CitizenProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.WasteStation", b =>
                {
                    b.OwnsOne("EcoNexus.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("WasteStationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.HasKey("WasteStationId");

                            b1.ToTable("WasteStations");

                            b1.WithOwner()
                                .HasForeignKey("WasteStationId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("EcoNexus.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("EcoNexus.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("EcoNexus.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("EcoNexus.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoNexus.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("EcoNexus.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.CitizenProfile", b =>
                {
                    b.Navigation("Classifications");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.CollectionJob", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.RecyclingFacility", b =>
                {
                    b.Navigation("Intakes");
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.WasteStation", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
