// <auto-generated />
using System;
using EcoNexus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoNexus.Infrastructure.Migrations
{
    [DbContext(typeof(EcoNexusDbContext))]
    [Migration("20260917125548_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoNexus.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("AcknowledgedAt");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AcknowledgedBy");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Message");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("RaisedAt");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ResolvedAt");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ResolvedBy");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Severity");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StationId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("StationId")
                        .HasDatabaseName("IX_Alerts_StationId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Alerts_Status");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.CitizenReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("AcknowledgedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Description");

                    b.Property<DateTimeOffset>("FiledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("FiledAt");

                    b.Property<Guid>("FiledByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FiledByUserId");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("PhotoUrl");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("ResolutionNote");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ResolvedAt");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StationId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("FiledByUserId")
                        .HasDatabaseName("IX_CitizenReports_FiledByUserId");

                    b.HasIndex("StationId")
                        .HasDatabaseName("IX_CitizenReports_StationId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_CitizenReports_Status");

                    b.ToTable("CitizenReports", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.CollectionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CompletedAt");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ScheduledFor");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("StartedAt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("VehicleId");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_CollectionJobs_Status");

                    b.HasIndex("VehicleId", "ScheduledFor")
                        .HasDatabaseName("IX_CollectionJobs_VehicleId_ScheduledFor");

                    b.ToTable("CollectionJobs", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.CollectionVehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Capacity")
                        .HasColumnType("float")
                        .HasColumnName("CapacityKilograms");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RegistrationNumber");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectionVehicles_RegistrationNumber");

                    b.ToTable("CollectionVehicles", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.RouteStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("CollectedWeight")
                        .HasColumnType("float")
                        .HasColumnName("CollectedWeightKilograms");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CompletedAt");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("JobId");

                    b.Property<int>("Sequence")
                        .HasColumnType("int")
                        .HasColumnName("Sequence");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StationId");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Sequence")
                        .HasDatabaseName("IX_RouteStops_JobId_Sequence");

                    b.ToTable("RouteStops", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.StationReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BatteryPercent")
                        .HasColumnType("int")
                        .HasColumnName("BatteryPercent");

                    b.Property<double>("FillLevel")
                        .HasColumnType("float")
                        .HasColumnName("FillLevelPercent");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("RecordedAt");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StationId");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("float")
                        .HasColumnName("TemperatureCelsius");

                    b.HasKey("Id");

                    b.HasIndex("StationId", "RecordedAt")
                        .HasDatabaseName("IX_StationReadings_StationId_RecordedAt");

                    b.ToTable("StationReadings", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.WasteStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Capacity")
                        .HasColumnType("float")
                        .HasColumnName("CapacityKilograms");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Code");

                    b.Property<double>("CurrentFill")
                        .HasColumnType("float")
                        .HasColumnName("CurrentFillPercent");

                    b.Property<DateTimeOffset?>("LastCollectedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastCollectedAt");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastUpdatedAt");

                    b.Property<string>("PrimaryCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("PrimaryCategory");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_WasteStations_Code");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_WasteStations_Status");

                    b.ToTable("WasteStations", (string)null);
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.RouteStop", b =>
                {
                    b.HasOne("EcoNexus.Domain.Entities.CollectionJob", null)
                        .WithMany("Stops")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.StationReading", b =>
                {
                    b.HasOne("EcoNexus.Domain.Entities.WasteStation", null)
                        .WithMany("Readings")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.WasteStation", b =>
                {
                    b.OwnsOne("EcoNexus.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("WasteStationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.HasKey("WasteStationId");

                            b1.ToTable("WasteStations");

                            b1.WithOwner()
                                .HasForeignKey("WasteStationId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.CollectionJob", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("EcoNexus.Domain.Entities.WasteStation", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
