<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EcoNexus.Domain\EcoNexus.Domain.csproj" />
    <ProjectReference Include="..\..\src\EcoNexus.Application\EcoNexus.Application.csproj" />
  </ItemGroup>

</Project>